# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Terminal-LLM',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/Terminal-LLM',
                'lib_path': 'Terminal_LLM'},
  'syms': {'Terminal_LLM.core': {'Terminal_LLM.core.foo': ('core.html#foo', 'Terminal_LLM/core.py')}}}
