# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Terminal-LLM',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/Terminal-LLM',
                'lib_path': 'Terminal_LLM'},
  'syms': { 'Terminal_LLM.chat': { 'Terminal_LLM.chat.Chat': ('chat.html#chat', 'Terminal_LLM/chat.py'),
                                   'Terminal_LLM.chat.Chat.__call__': ('chat.html#chat.__call__', 'Terminal_LLM/chat.py'),
                                   'Terminal_LLM.chat.Chat.__init__': ('chat.html#chat.__init__', 'Terminal_LLM/chat.py'),
                                   'Terminal_LLM.chat.Chat.write_history': ('chat.html#chat.write_history', 'Terminal_LLM/chat.py')}}}
