# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_chat.ipynb.

# %% auto 0
__all__ = ['Chat']

# %% ../nbs/00_chat.ipynb 30
from mistralai.client import MistralClient


# %% ../nbs/00_chat.ipynb 32
from mistralai.models.chat_completion import ChatMessage


# %% ../nbs/00_chat.ipynb 54
from fastcore.all import *


# %% ../nbs/00_chat.ipynb 58
class Chat:
  def __init__(self, api_key, model): 
    self.client = MistralClient(api_key=api_key)
    self.model = model
    self.history = []


  def __call__(self, query): 
    messages = self.history + [ChatMessage(role='user', content=query)]
    response = self.client.chat(model=self.model, messages=messages).choices[0].message.content
    self.write_history(query, response)
    return response
  
  
  def write_history(self, query, response):
    self.history.append(ChatMessage(role='user', content=query))
    self.history.append(ChatMessage(role='assistant', content=response))
